{% set version = "26.14.0" %}

# from `sqlglotrs/Cargo.toml#package/version`
{% set sqlglotrs_version = "0.4.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: sqlglot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sqlglot/sqlglot-{{ version }}.tar.gz
  sha256: 7c75e28cb5c245ed3b3d995c2affcc6d5975e2ca8ec052fe132b8e5287e72c61

build:
  number: 0
  noarch: python

outputs:
  - name: sqlglot
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools_scm
        - setuptools
      run:
        - python >={{ python_min }}
      run_constrained:
        - sqlglotrs {{ sqlglotrs_version }}

    test:
      source_files:
        - tests
      imports:
        - sqlglot
      commands:
        - pip check
        - pytest -vvv --capture=tee-sys --color=yes --tb=long tests
      requires:
        - openjdk
        - pandas
        - pip
        - pyspark
        - pytest
        - python-dateutil
        - python {{ python_min }}

  - name: sqlglot-rs
    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('sqlglot', exact=True) }}
        - sqlglotrs

    test:
      files:
        - test_sqlglotrs_version.py
      source_files:
        - tests
        - sqlglotrs/Cargo.toml
      imports:
        - sqlglot
      commands:
        - pip check
        - pytest -vvv --capture=tee-sys --color=yes --tb=long test_sqlglotrs_version.py
        - pytest -vvv --capture=tee-sys --color=yes --tb=long tests
      requires:
        - openjdk
        - pandas
        - pip
        - pyspark
        - pytest
        - python-dateutil
        - python-duckdb >=0.6
        # for checking sqlglotrs version against Cargo.toml
        - tomli
        - python {{ python_min }}

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
